# Etapa 1: Compilación con Maven
FROM maven:3.9.6-eclipse-temurin-17 AS builder

WORKDIR /app

# Copiamos los archivos necesarios
COPY pom.xml .
COPY .mvn .mvn
COPY mvnw .
COPY src ./src

# Compilamos el proyecto y generamos el .jar
RUN ./mvnw clean package -DskipTests

# Etapa 2: Imagen final (liviana)
FROM eclipse-temurin:17-jdk-jammy

WORKDIR /app

# Copiamos el .jar desde el contenedor de build
COPY --from=builder /app/target/ms-mascotas-0.0.1-SNAPSHOT.jar app.jar

# Puerto por defecto usado por gRPC
EXPOSE 9090

# Comando para ejecutar la app
ENTRYPOINT ["java", "-jar", "app.jar"]
